// Code generated by MockGen. DO NOT EDIT.
// Source: ../auth/delivery/http_handler.go
//
// Generated by this command:
//
//	mockgen -source=../auth/delivery/http_handler.go -destination=auth_delivery.go -package=mocks -mock_names=Service=MockAuthDeliveryService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthDeliveryService is a mock of Service interface.
type MockAuthDeliveryService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthDeliveryServiceMockRecorder
	isgomock struct{}
}

// MockAuthDeliveryServiceMockRecorder is the mock recorder for MockAuthDeliveryService.
type MockAuthDeliveryServiceMockRecorder struct {
	mock *MockAuthDeliveryService
}

// NewMockAuthDeliveryService creates a new mock instance.
func NewMockAuthDeliveryService(ctrl *gomock.Controller) *MockAuthDeliveryService {
	mock := &MockAuthDeliveryService{ctrl: ctrl}
	mock.recorder = &MockAuthDeliveryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthDeliveryService) EXPECT() *MockAuthDeliveryServiceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthDeliveryService) Login(ctx context.Context, email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthDeliveryServiceMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthDeliveryService)(nil).Login), ctx, email, password)
}
