// Code generated by MockGen. DO NOT EDIT.
// Source: ../transactions/domain/transaction.go
//
// Generated by this command:
//
//	mockgen -source=../transactions/domain/transaction.go -destination=transaction.go -package=mocks -mock_names=Repository=MockTransactionRepository,CodeGenerator=MockCodeGenerator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/afryn123/withdraw-service-test/internal/transactions/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRepository is a mock of Repository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTransactionRepository) Create(ctx context.Context, transaction *domain.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTransactionRepositoryMockRecorder) Create(ctx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTransactionRepository)(nil).Create), ctx, transaction)
}

// MockCodeGenerator is a mock of CodeGenerator interface.
type MockCodeGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockCodeGeneratorMockRecorder
	isgomock struct{}
}

// MockCodeGeneratorMockRecorder is the mock recorder for MockCodeGenerator.
type MockCodeGeneratorMockRecorder struct {
	mock *MockCodeGenerator
}

// NewMockCodeGenerator creates a new mock instance.
func NewMockCodeGenerator(ctrl *gomock.Controller) *MockCodeGenerator {
	mock := &MockCodeGenerator{ctrl: ctrl}
	mock.recorder = &MockCodeGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeGenerator) EXPECT() *MockCodeGeneratorMockRecorder {
	return m.recorder
}

// ReferenceNumber mocks base method.
func (m *MockCodeGenerator) ReferenceNumber(userID uuid.UUID) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReferenceNumber", userID)
	ret0, _ := ret[0].(string)
	return ret0
}

// ReferenceNumber indicates an expected call of ReferenceNumber.
func (mr *MockCodeGeneratorMockRecorder) ReferenceNumber(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReferenceNumber", reflect.TypeOf((*MockCodeGenerator)(nil).ReferenceNumber), userID)
}

// TransactionCode mocks base method.
func (m *MockCodeGenerator) TransactionCode() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionCode")
	ret0, _ := ret[0].(string)
	return ret0
}

// TransactionCode indicates an expected call of TransactionCode.
func (mr *MockCodeGeneratorMockRecorder) TransactionCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionCode", reflect.TypeOf((*MockCodeGenerator)(nil).TransactionCode))
}
