// Code generated by MockGen. DO NOT EDIT.
// Source: ../transactions/delivery/http_handler.go
//
// Generated by this command:
//
//	mockgen -source=../transactions/delivery/http_handler.go -destination=transaction_delivery.go -package=mocks -mock_names=Service=MockTransactionDeliveryService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	application "github.com/afryn123/withdraw-service-test/internal/transactions/application"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionDeliveryService is a mock of Service interface.
type MockTransactionDeliveryService struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionDeliveryServiceMockRecorder
	isgomock struct{}
}

// MockTransactionDeliveryServiceMockRecorder is the mock recorder for MockTransactionDeliveryService.
type MockTransactionDeliveryServiceMockRecorder struct {
	mock *MockTransactionDeliveryService
}

// NewMockTransactionDeliveryService creates a new mock instance.
func NewMockTransactionDeliveryService(ctrl *gomock.Controller) *MockTransactionDeliveryService {
	mock := &MockTransactionDeliveryService{ctrl: ctrl}
	mock.recorder = &MockTransactionDeliveryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionDeliveryService) EXPECT() *MockTransactionDeliveryServiceMockRecorder {
	return m.recorder
}

// Withdraw mocks base method.
func (m *MockTransactionDeliveryService) Withdraw(ctx context.Context, userID uuid.UUID, amount int64, remark *string) (application.WithdrawResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, userID, amount, remark)
	ret0, _ := ret[0].(application.WithdrawResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockTransactionDeliveryServiceMockRecorder) Withdraw(ctx, userID, amount, remark any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockTransactionDeliveryService)(nil).Withdraw), ctx, userID, amount, remark)
}
