// Code generated by MockGen. DO NOT EDIT.
// Source: ../user/delivery/http_handler.go
//
// Generated by this command:
//
//	mockgen -source=../user/delivery/http_handler.go -destination=user_delivery.go -package=mocks -mock_names=Service=MockUserDeliveryService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	application "github.com/afryn123/withdraw-service-test/internal/user/application"
	gomock "go.uber.org/mock/gomock"
)

// MockUserDeliveryService is a mock of Service interface.
type MockUserDeliveryService struct {
	ctrl     *gomock.Controller
	recorder *MockUserDeliveryServiceMockRecorder
	isgomock struct{}
}

// MockUserDeliveryServiceMockRecorder is the mock recorder for MockUserDeliveryService.
type MockUserDeliveryServiceMockRecorder struct {
	mock *MockUserDeliveryService
}

// NewMockUserDeliveryService creates a new mock instance.
func NewMockUserDeliveryService(ctrl *gomock.Controller) *MockUserDeliveryService {
	mock := &MockUserDeliveryService{ctrl: ctrl}
	mock.recorder = &MockUserDeliveryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDeliveryService) EXPECT() *MockUserDeliveryServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserDeliveryService) Create(ctx context.Context, command application.CreateUserCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserDeliveryServiceMockRecorder) Create(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserDeliveryService)(nil).Create), ctx, command)
}

// Delete mocks base method.
func (m *MockUserDeliveryService) Delete(ctx context.Context, command application.DeleteUserCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserDeliveryServiceMockRecorder) Delete(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserDeliveryService)(nil).Delete), ctx, command)
}

// Update mocks base method.
func (m *MockUserDeliveryService) Update(ctx context.Context, command application.UpdateUserCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserDeliveryServiceMockRecorder) Update(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserDeliveryService)(nil).Update), ctx, command)
}
