// Code generated by MockGen. DO NOT EDIT.
// Source: ../wallet/delivery/http_handler.go
//
// Generated by this command:
//
//	mockgen -source=../wallet/delivery/http_handler.go -destination=wallet_delivery.go -package=mocks -mock_names=Service=MockWalletDeliveryService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	application "github.com/afryn123/withdraw-service-test/internal/wallet/application"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockWalletDeliveryService is a mock of Service interface.
type MockWalletDeliveryService struct {
	ctrl     *gomock.Controller
	recorder *MockWalletDeliveryServiceMockRecorder
	isgomock struct{}
}

// MockWalletDeliveryServiceMockRecorder is the mock recorder for MockWalletDeliveryService.
type MockWalletDeliveryServiceMockRecorder struct {
	mock *MockWalletDeliveryService
}

// NewMockWalletDeliveryService creates a new mock instance.
func NewMockWalletDeliveryService(ctrl *gomock.Controller) *MockWalletDeliveryService {
	mock := &MockWalletDeliveryService{ctrl: ctrl}
	mock.recorder = &MockWalletDeliveryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletDeliveryService) EXPECT() *MockWalletDeliveryServiceMockRecorder {
	return m.recorder
}

// FindBalanceByUserID mocks base method.
func (m *MockWalletDeliveryService) FindBalanceByUserID(ctx context.Context, userID uuid.UUID) (application.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBalanceByUserID", ctx, userID)
	ret0, _ := ret[0].(application.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBalanceByUserID indicates an expected call of FindBalanceByUserID.
func (mr *MockWalletDeliveryServiceMockRecorder) FindBalanceByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBalanceByUserID", reflect.TypeOf((*MockWalletDeliveryService)(nil).FindBalanceByUserID), ctx, userID)
}
